setwd("AnalyticsEdge/Unit 6/")
data=read.csv("dailykos.csv")
distance = dist(data, method="euclidean")
cluster = hclust(distance, method="ward.D")
plot(cluster)

AllClusters = cutree(cluster, k=7)
Cluster1 = subset(data, AllClusters == 1)
Cluster2 = subset(data, AllClusters == 2)
Cluster3 = subset(data, AllClusters == 3)
Cluster4 = subset(data, AllClusters == 4)
Cluster5 = subset(data, AllClusters == 5)
Cluster6 = subset(data, AllClusters == 6)
Cluster7 = subset(data, AllClusters == 7)

nrow(Cluster1)
nrow(Cluster2)
nrow(Cluster3)
nrow(Cluster4)
nrow(Cluster5)
nrow(Cluster6)
nrow(Cluster7)

tail(sort(colMeans(Cluster1)))
tail(sort(colMeans(Cluster2)))
tail(sort(colMeans(Cluster3)))
tail(sort(colMeans(Cluster4)))
tail(sort(colMeans(Cluster5)))
tail(sort(colMeans(Cluster6)))
tail(sort(colMeans(Cluster7)))


set.seed(1000)
clusters = kmeans(data, centers=7)
KMC = clusters$cluster

Cluster1 = subset(data,KMC == 1)
Cluster2 = subset(data,KMC == 2)
Cluster3 = subset(data,KMC == 3)
Cluster4 = subset(data,KMC == 4)
Cluster5 = subset(data,KMC == 5)
Cluster6 = subset(data,KMC == 6)
Cluster7 = subset(data,KMC == 7)

nrow(Cluster1)
nrow(Cluster2)
nrow(Cluster3)
nrow(Cluster4)
nrow(Cluster5)
nrow(Cluster6)
nrow(Cluster7)

tail(sort(colMeans(Cluster1)))
tail(sort(colMeans(Cluster2)))
tail(sort(colMeans(Cluster3)))
tail(sort(colMeans(Cluster4)))
tail(sort(colMeans(Cluster5)))
tail(sort(colMeans(Cluster6)))
tail(sort(colMeans(Cluster7)))
