letters = read.csv("AnalyticsEdge/Assigment3/letters_ABPR.csv")
summary(letters)
isB = subset(letters, letters$letter == 'B')
letters$isB = as.factor(letters$letter == 'B')

set.seed(1000)
library(caTools)
spl = sample.split(letters$isB, SplitRatio = 0.5)
Train = subset(letters, spl == TRUE)
Test = subset(letters, spl == FALSE)
table(Test$isB)
1175/(1175+383)


library(rpart)
library(rpart.plot)
CARTb = rpart(isB ~ . - letter, data = Train, method="class")
summary(CARTb)
PredictTest = predict(CARTb, newdata = Test, type="class")
table(Test$isB, PredictTest)
(1130+321) / (1130+45+62+321)

library(randomForest)
RF = randomForest(isB ~ . - letter, data = Train)
PredictTestRF = predict(RF, newdata = Test)
table(Test$isB, PredictTestRF)
(1171+362) / (1171+4+21+362)


letters$letter = as.factor(letters$letter)
set.seed(2000)
spl = sample.split(letters$isB, SplitRatio = 0.5)
Train = subset(letters, spl == TRUE)
Test = subset(letters, spl == FALSE)
table(Test$letter)
(397) / (394+383+397+384)
CART = rpart(letter ~ . - isB, data=Train, method="class")
PredictedCART = predict(CART, newdata=Test, type="class")
table(Test$letter, PredictedCART)
(345+317+360+332) / (345+20+0+29+9+317+12+45+4+28+360+5+6+43+3+332)
summary(CART)

set.seed(1000)
RF2 = randomForest(letter ~ . - isB, data=Train)
PredictedRF2 = predict(RF2, newdata=Test, type="class")
table(Test$letter, PredictedRF2)
(392+380+390+373) / nrow(Test)
